name: flutter_test_incode_groupe_hogwarts_hat_08_24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2758.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3 
  http: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: HarryP
      fonts:
        - asset: fonts/harryP.ttf
  assets:
    - assets/
